Making trip view scrollable
googleinterns/step23-2020 pull request #114
Opened 2020-07-27 21:35 UTC by anfee1

Small change making the trip view a scrollable object.

2020-07-27 21:41 UTC, cli1903 approved these changes

2020-07-28 02:18 UTC, bsidhom requested changes

2020-07-28 02:18 UTC, bsidhom commented on frontend/ui/lib/widgets/trip_view_widget.dart
> +      child: SingleChildScrollView(
Have you tried using a [`ListView`](https://api.flutter.dev/flutter/widgets/ListView-class.html) here? That should effectively merge the behavior of the scroll view and column. `ListView` also allows additional customization for scroll/display behavior.

2020-07-28 19:49 UTC, KoopaKing approved these changes

2020-07-28 19:50 UTC, bsidhom approved these changes
LGTM

2020-07-28 19:50 UTC, merged