create Place service to handle external api calls
googleinterns/step23-2020 pull request #91
Opened 2020-07-21 19:09 UTC by cli1903

2020-07-21 19:37 UTC, chuckluv submitted a review, later dismissed
LGTM just a couple of nits

2020-07-21 19:37 UTC, chuckluv commented on frontend/src/main/java/com/google/tripmeout/frontend/service/PlaceService.java
> +}
nit:new line at end of file

2020-07-21 19:37 UTC, chuckluv commented on frontend/src/main/java/com/google/tripmeout/frontend/service/PlacesApiPlaceService.java
> +}
nit:new line at end of file

2020-07-21 19:37 UTC, chuckluv commented on frontend/src/test/java/com/google/tripmeout/frontend/service/PlaceServiceTest.java
> +}
nit:new line at end of file

2020-07-22 18:05 UTC, bsidhom requested changes

2020-07-22 18:05 UTC, bsidhom commented on frontend/src/main/java/com/google/tripmeout/frontend/service/PlaceService.java
> +      throws ApiException, InterruptedException, IOException;
This interface should be agnostic to the underlying implementation. In particular, we should not expose Maps API exceptions. Throwing interruption exceptions _might_ make sense if we expect operations to potentially block for a while.

Further, if validation failure should _always_ result in a client error, consider throwing an exception if the validation comes back negative rather than returning a boolean (which is easy to forget to check). I would keep the boolean if you think there will be situations where we want to change behavior following a validation failure but _not_ immediately stop computation and return an error to the client (seems unlikely, but possible).

2020-07-22 18:05 UTC, bsidhom commented on frontend/src/main/java/com/google/tripmeout/frontend/service/PlaceService.java
> +package com.google.tripmeout.frontend.service;
This should go under a more descriptive package name. Maybe `com.google.tripmeout.frontend.maps` or `com.google.frontend.places`.

2020-07-22 18:05 UTC, bsidhom commented on frontend/src/main/java/com/google/tripmeout/frontend/service/PlaceServiceModule.java
> +    return new GeoApiContext.Builder().apiKey("APIKEY").build();
Please talk to @KoopaKing about how this should actually get resolved. For now, it might make sense to have this actually pull from an environment variable. We'll probably want this to come from a local config file down the line, but no need to add that here.

2020-07-22 18:05 UTC, bsidhom commented on frontend/src/test/java/com/google/tripmeout/frontend/service/PlaceServiceTest.java
> +//@RunWith(JUnit4.class)
Keep this annotation.

2020-07-22 18:05 UTC, bsidhom commented on frontend/src/test/java/com/google/tripmeout/frontend/service/PlaceServiceTest.java
> +  public void validatePlaceId_invalidPlaceId_returnsFalse()
You can keep the `@Test` annotations here and below and _add_ the `@Ignore` annotation. This will still prevent the tests from running by default.

2020-07-22 18:05 UTC, bsidhom commented on frontend/src/test/java/com/google/tripmeout/frontend/service/PlaceServiceTest.java
> +  Injector injector = Guice.createInjector(new PlaceServiceModule());
Please initialize all these fields in a `@Before`-annotated setup method and do not retain the injector itself. You also shouldn't need an explicit `GeoApiContext` either.

 For example:

```java
@Inject
private PlaceService placeService;

@Before
public void setUp() {
  Injector injector = Guice.createInjector(new PlaceServiceModule());
  injector.injectMembers(this);
}
```

2020-07-22 18:05 UTC, bsidhom commented on frontend/src/main/java/com/google/tripmeout/frontend/service/PlacesApiPlaceService.java
> +@Singleton
Note: this service does not technically require a singleton binding. You can imagine scenarios where you might want multiple place services, e.g., initialized with different API keys (contexts).

Instead, the singleton scope should be added to the module binding.

2020-07-22 18:05 UTC, bsidhom commented on frontend/src/main/java/com/google/tripmeout/frontend/service/PlaceServiceModule.java
> +public class PlaceServiceModule extends AbstractModule {
Please add a binding for the `PlaceService` itself.

2020-07-22 18:05 UTC, bsidhom commented on frontend/src/main/java/com/google/tripmeout/frontend/service/PlaceServiceModule.java
> +public class PlaceServiceModule extends AbstractModule {
Consider renaming this module to reflect the fact that it's binding the real maps API service (rather than, e.g., some sort of in-memory fake.

2020-07-22 20:24 UTC, bsidhom submitted a review, later dismissed
Should be good after some exception translation.

2020-07-22 20:24 UTC, bsidhom commented on frontend/src/main/java/com/google/tripmeout/frontend/places/PlacesApiPlaceService.java
> +    request.await();
Please continue to catch `InvalidRequestException` and translate it into an appropriate domain-specific exception here. The idea is to mask our dependencies/implementation details and have client code only use what it needs. You may want to mint a new exception type if we don't already have something that makes sense for this situation.

2020-07-22 20:24 UTC, bsidhom commented on frontend/src/main/java/com/google/tripmeout/frontend/places/PlaceService.java
> +  void validatePlaceId(String placesApiPlaceId) throws Exception;
This should probably throw a more precise validation exception (and possibly IOException, if appropriate).

2020-07-23 15:43 UTC, chuckluv commented on frontend/src/main/java/com/google/tripmeout/frontend/error/PlacesApiRequestException.java
> +}
nit: new line at end of file

2020-07-23 15:44 UTC, chuckluv submitted a review, later dismissed
LGTM

2020-07-23 18:17 UTC, KoopaKing submitted a review, later dismissed

2020-07-23 19:39 UTC, anfee1 approved these changes
LGTM

2020-07-23 20:37 UTC, KoopaKing approved these changes

2020-07-23 20:39 UTC, merged